# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': '目录管理', 'verbose_name_plural': '目录管理'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '指标')], help_text='目录级别', verbose_name='目录级别'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='category.CategoryModel', verbose_name='所属父目录'),
        ),
    ]
