# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20181115_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category_type',
        ),
    ]
