# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_categorymodel_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_index',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否是指标'),
        ),
    ]
