# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上次登录IP'),
        ),
    ]
