# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmodel',
            name='formula',
            field=models.CharField(default='', help_text='计算公式', max_length=200),
        ),
    ]
