# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_stepmodel_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type_name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
