# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_auto_20190102_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StepData',
        ),
    ]
