# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20181115_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='指标名称', help_text='指标名称', max_length=20, verbose_name='指标名称')),
                ('category', models.ForeignKey(help_text='指标', on_delete=django.db.models.deletion.CASCADE, to='category.CategoryModel', verbose_name='指标名称')),
            ],
        ),
    ]
