# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='指标', on_delete=django.db.models.deletion.CASCADE, to='category.CategoryModel', verbose_name='指标名称'),
        ),
    ]
